from __future__ import annotations

import argparse
import json
from datetime import datetime
from pathlib import Path

import pandas as pd


class ReportBuildError(RuntimeError):
    def __init__(self, message: str, details: dict[str, str] | None = None) -> None:
        context = ""
        if details:
            pairs = ", ".join(f"{key}={value}" for key, value in sorted(details.items()))
            context = f" [{pairs}]"
        super().__init__(f"{message}{context}")


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Build markdown report for stock-pool review results")
    parser.add_argument("--baseline-a-raw", required=True, help="Annual segmented raw CSV for production baseline")
    parser.add_argument("--baseline-a-rank", required=True, help="Continuous stability rank CSV for production baseline")
    parser.add_argument("--baseline-a-name", required=True, help="Universe name to use for production baseline")
    parser.add_argument("--baseline-b-raw", required=True, help="Annual segmented raw CSV for 1321 baseline")
    parser.add_argument("--baseline-b-rank", required=True, help="Continuous stability rank CSV for 1321 baseline")
    parser.add_argument("--baseline-b-name", required=True, help="Universe name to use for 1321 baseline")
    parser.add_argument("--comparison-raw", required=True, help="Annual segmented raw CSV for multi-pool comparison run")
    parser.add_argument("--comparison-rank", required=True, help="Continuous stability rank CSV for multi-pool comparison run")
    parser.add_argument("--pool-summary-csv", help="Optional pool summary CSV generated by build_stock_pools.py")
    parser.add_argument("--fetch-summary", help="Optional JSON summary from the full-market fetch step")
    parser.add_argument("--commands-file", help="Optional text or markdown file containing the executed commands")
    parser.add_argument("--output", required=True, help="Markdown report output path")
    return parser.parse_args()


def _read_csv(path_value: str) -> pd.DataFrame:
    path = Path(path_value)
    if not path.exists():
        raise ReportBuildError("CSV file does not exist", {"path": str(path)})
    return pd.read_csv(path)


def _ensure_universe_name(frame: pd.DataFrame, fallback_name: str) -> pd.DataFrame:
    normalized = frame.copy()
    if "universe_name" not in normalized.columns:
        normalized["universe_name"] = fallback_name
        return normalized

    normalized["universe_name"] = (
        normalized["universe_name"]
        .fillna(fallback_name)
        .astype(str)
        .str.strip()
        .replace("", fallback_name)
    )
    return normalized


def _numeric_series(frame: pd.DataFrame, column: str) -> pd.Series:
    if column not in frame.columns:
        return pd.Series([float("nan")] * len(frame), index=frame.index, dtype="float64")
    return pd.to_numeric(frame[column], errors="coerce")


def _positive_count(series: pd.Series) -> int:
    return int((pd.to_numeric(series, errors="coerce") > 0).sum())


def _summarize_raw(frame: pd.DataFrame) -> pd.DataFrame:
    working = frame.copy()
    numeric_columns = [
        "return_pct",
        "alpha",
        "max_drawdown_pct",
        "sharpe_ratio",
        "win_rate_pct",
        "num_trades",
    ]
    for column in numeric_columns:
        working[column] = _numeric_series(working, column)

    grouped = (
        working.groupby("universe_name", as_index=False)
        .agg(
            avg_yearly_return_pct=("return_pct", "mean"),
            avg_yearly_alpha_pct=("alpha", "mean"),
            avg_yearly_mdd_pct=("max_drawdown_pct", "mean"),
            avg_yearly_sharpe_ratio=("sharpe_ratio", "mean"),
            avg_yearly_win_rate_pct=("win_rate_pct", "mean"),
            total_yearly_trades=("num_trades", "sum"),
            worst_year_return_pct=("return_pct", "min"),
            best_year_return_pct=("return_pct", "max"),
            positive_years=("return_pct", _positive_count),
        )
        .reset_index(drop=True)
    )
    return grouped


def _summarize_rank(frame: pd.DataFrame) -> pd.DataFrame:
    working = frame.copy()
    if "continuous_stability_rank" in working.columns:
        working = working.sort_values("continuous_stability_rank", ascending=True)
    elif "continuous_return_pct" in working.columns:
        working = working.sort_values("continuous_return_pct", ascending=False)

    keep_columns = [
        "universe_name",
        "continuous_stability_rank",
        "continuous_return_pct",
        "continuous_alpha_pct",
        "continuous_mdd_pct",
        "continuous_sharpe_ratio",
        "continuous_win_rate_pct",
        "continuous_num_trades",
        "annual_return_std_pct",
        "positive_alpha_years",
        "entry_strategy",
        "exit_strategy",
        "position_profile",
        "overlay_mode",
        "continuous_start_date",
        "continuous_end_date",
    ]
    available = [column for column in keep_columns if column in working.columns]
    if "universe_name" not in available:
        raise ReportBuildError("Rank CSV lacks universe_name after normalization")
    grouped = working[available].groupby("universe_name", as_index=False).first()
    return grouped


def _merge_summary(raw_summary: pd.DataFrame, rank_summary: pd.DataFrame) -> pd.DataFrame:
    return raw_summary.merge(rank_summary, on="universe_name", how="outer")


def _load_optional_pool_summary(path_value: str | None) -> pd.DataFrame | None:
    if not path_value:
        return None
    frame = _read_csv(path_value)
    if "pool_name" not in frame.columns:
        raise ReportBuildError("Pool summary CSV missing pool_name", {"path": path_value})
    return frame


def _load_optional_text(path_value: str | None) -> str | None:
    if not path_value:
        return None
    path = Path(path_value)
    if not path.exists():
        raise ReportBuildError("Text file does not exist", {"path": str(path)})
    return path.read_text(encoding="utf-8")


def _load_optional_json(path_value: str | None) -> dict[str, object] | None:
    if not path_value:
        return None
    path = Path(path_value)
    if not path.exists():
        raise ReportBuildError("JSON file does not exist", {"path": str(path)})
    with open(path, "r", encoding="utf-8") as handle:
        payload = json.load(handle)
    if not isinstance(payload, dict):
        raise ReportBuildError("JSON summary must be an object", {"path": str(path)})
    return payload


def _round_frame(frame: pd.DataFrame, digits: int = 4) -> pd.DataFrame:
    rounded = frame.copy()
    for column in rounded.columns:
        if pd.api.types.is_numeric_dtype(rounded[column]):
            rounded[column] = rounded[column].round(digits)
    return rounded


def _to_markdown_table(frame: pd.DataFrame, columns: list[str]) -> str:
    subset = frame[[column for column in columns if column in frame.columns]].copy()
    if subset.empty or not subset.columns.tolist():
        return "_No data available._"

    header = "| " + " | ".join(subset.columns.tolist()) + " |"
    separator = "| " + " | ".join(["---"] * len(subset.columns)) + " |"
    rows: list[str] = []
    for _, row in subset.iterrows():
        values: list[str] = []
        for column in subset.columns:
            value = row[column]
            if pd.isna(value):
                values.append("")
            elif isinstance(value, float):
                values.append(f"{value:.4f}".rstrip("0").rstrip("."))
            else:
                values.append(str(value))
        rows.append("| " + " | ".join(values) + " |")
    return "\n".join([header, separator] + rows)


def _append_delta_columns(
    frame: pd.DataFrame,
    baseline_row: pd.Series,
    prefix: str,
    metric_columns: list[str],
) -> pd.DataFrame:
    enriched = frame.copy()
    for column in metric_columns:
        if column not in enriched.columns or column not in baseline_row.index:
            continue
        baseline_value = pd.to_numeric(pd.Series([baseline_row[column]]), errors="coerce").iloc[0]
        if pd.isna(baseline_value):
            continue
        enriched[f"{prefix}_{column}_delta"] = _numeric_series(enriched, column) - float(baseline_value)
    return enriched


def _get_named_row(frame: pd.DataFrame, universe_name: str) -> pd.Series:
    matched = frame[frame["universe_name"] == universe_name]
    if matched.empty:
        raise ReportBuildError("Universe not found in summary", {"universe_name": universe_name})
    return matched.iloc[0]


def _merge_pool_summary(frame: pd.DataFrame, pool_summary: pd.DataFrame | None) -> pd.DataFrame:
    if pool_summary is None:
        return frame
    return frame.merge(pool_summary, left_on="universe_name", right_on="pool_name", how="left")


def _sorted_summary(frame: pd.DataFrame) -> pd.DataFrame:
    sort_columns = [
        column
        for column in [
            "continuous_return_pct",
            "continuous_alpha_pct",
            "avg_yearly_alpha_pct",
            "avg_yearly_return_pct",
        ]
        if column in frame.columns
    ]
    if not sort_columns:
        return frame.copy()
    ascending = [False] * len(sort_columns)
    return frame.sort_values(sort_columns, ascending=ascending, kind="mergesort").reset_index(drop=True)


def _format_fetch_summary(payload: dict[str, object] | None) -> str:
    if not payload:
        return "- Not supplied\n"
    lines: list[str] = []
    for key in sorted(payload):
        value = payload[key]
        if isinstance(value, (str, int, float, bool)) or value is None:
            lines.append(f"- {key}: {value}")
    return "\n".join(lines) + "\n"


def _build_observations(
    summary: pd.DataFrame,
    baseline_a_name: str,
    baseline_b_name: str,
) -> list[str]:
    candidate_frame = summary[~summary["universe_name"].isin([baseline_a_name, baseline_b_name])].copy()
    observations: list[str] = []
    if candidate_frame.empty:
        return ["No candidate pools were found in the comparison summary."]

    top_candidate = candidate_frame.iloc[0]
    if "vs_prod_continuous_return_pct_delta" in top_candidate.index and not pd.isna(top_candidate["vs_prod_continuous_return_pct_delta"]):
        observations.append(
            f"Top candidate by continuous return is {top_candidate['universe_name']}, with continuous return delta "
            f"{float(top_candidate['vs_prod_continuous_return_pct_delta']):.2f} points vs production baseline."
        )
    else:
        observations.append(f"Top candidate by continuous return is {top_candidate['universe_name']}.")

    if "overlap_with_production" in top_candidate.index and not pd.isna(top_candidate["overlap_with_production"]):
        observations.append(
            f"{top_candidate['universe_name']} keeps {int(top_candidate['overlap_with_production'])} names overlapping the production baseline."
        )

    if "avg_yearly_mdd_pct" in candidate_frame.columns:
        safest = candidate_frame.sort_values("avg_yearly_mdd_pct", ascending=True).iloc[0]
        observations.append(
            f"Lowest average yearly drawdown among candidates is {safest['universe_name']} at {float(safest['avg_yearly_mdd_pct']):.2f}%."
        )

    sector_candidates = candidate_frame[
        candidate_frame["universe_name"].astype(str).str.startswith("sector33x3p1_")
    ]
    if not sector_candidates.empty and "continuous_return_pct" in sector_candidates.columns:
        best_sector = sector_candidates.sort_values("continuous_return_pct", ascending=False).iloc[0]
        observations.append(
            f"Best sector-balanced pool is {best_sector['universe_name']} with continuous return {float(best_sector['continuous_return_pct']):.2f}%."
        )

    return observations


def main() -> None:
    args = _parse_args()

    baseline_a_raw = _ensure_universe_name(_read_csv(args.baseline_a_raw), args.baseline_a_name)
    baseline_a_rank = _ensure_universe_name(_read_csv(args.baseline_a_rank), args.baseline_a_name)
    baseline_b_raw = _ensure_universe_name(_read_csv(args.baseline_b_raw), args.baseline_b_name)
    baseline_b_rank = _ensure_universe_name(_read_csv(args.baseline_b_rank), args.baseline_b_name)
    comparison_raw = _ensure_universe_name(_read_csv(args.comparison_raw), "comparison")
    comparison_rank = _ensure_universe_name(_read_csv(args.comparison_rank), "comparison")

    baseline_a_summary = _merge_summary(_summarize_raw(baseline_a_raw), _summarize_rank(baseline_a_rank))
    baseline_b_summary = _merge_summary(_summarize_raw(baseline_b_raw), _summarize_rank(baseline_b_rank))
    comparison_summary = _merge_summary(_summarize_raw(comparison_raw), _summarize_rank(comparison_rank))

    combined = pd.concat([comparison_summary, baseline_a_summary, baseline_b_summary], ignore_index=True)
    combined = combined.drop_duplicates(subset=["universe_name"], keep="last").reset_index(drop=True)

    baseline_a_row = _get_named_row(combined, args.baseline_a_name)
    baseline_b_row = _get_named_row(combined, args.baseline_b_name)

    delta_metrics = [
        "continuous_return_pct",
        "continuous_alpha_pct",
        "avg_yearly_return_pct",
        "avg_yearly_alpha_pct",
        "avg_yearly_mdd_pct",
    ]
    combined = _append_delta_columns(combined, baseline_a_row, "vs_prod", delta_metrics)
    combined = _append_delta_columns(combined, baseline_b_row, "vs_1321", delta_metrics)
    combined = _merge_pool_summary(combined, _load_optional_pool_summary(args.pool_summary_csv))
    combined = _sorted_summary(combined)

    baselines_table = combined[combined["universe_name"].isin([args.baseline_a_name, args.baseline_b_name])].copy()
    candidate_table = combined[~combined["universe_name"].isin([args.baseline_a_name, args.baseline_b_name])].copy()
    rounded_baselines = _round_frame(baselines_table)
    rounded_candidates = _round_frame(candidate_table)

    commands_text = _load_optional_text(args.commands_file)
    fetch_summary = _load_optional_json(args.fetch_summary)
    observations = _build_observations(combined, args.baseline_a_name, args.baseline_b_name)

    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    with open(output_path, "w", encoding="utf-8") as handle:
        handle.write("# Stock Pool Review Report\n\n")
        handle.write(f"Generated at: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n")

        handle.write("## Inputs\n\n")
        handle.write(f"- Production baseline: {args.baseline_a_name}\n")
        handle.write(f"- 1321 baseline: {args.baseline_b_name}\n")
        handle.write(f"- Candidate pool count: {len(candidate_table)}\n\n")

        handle.write("## Fetch Refresh Summary\n\n")
        handle.write(_format_fetch_summary(fetch_summary))
        handle.write("\n")

        handle.write("## Commands\n\n")
        if commands_text:
            handle.write("```text\n")
            handle.write(commands_text.rstrip())
            handle.write("\n```\n\n")
        else:
            handle.write("_No commands file supplied._\n\n")

        handle.write("## Baselines\n\n")
        handle.write(
            _to_markdown_table(
                rounded_baselines,
                [
                    "universe_name",
                    "continuous_return_pct",
                    "continuous_alpha_pct",
                    "avg_yearly_return_pct",
                    "avg_yearly_alpha_pct",
                    "avg_yearly_mdd_pct",
                    "positive_years",
                    "continuous_stability_rank",
                    "position_profile",
                    "overlay_mode",
                ],
            )
        )
        handle.write("\n\n")

        handle.write("## Pool Construction Summary\n\n")
        handle.write(
            _to_markdown_table(
                rounded_candidates,
                [
                    "universe_name",
                    "score_model",
                    "selection_rule",
                    "overlap_with_production",
                    "overlap_pct",
                    "unique_sector_count",
                    "top_additions",
                    "top_removals",
                ],
            )
        )
        handle.write("\n\n")

        handle.write("## Performance Comparison\n\n")
        handle.write(
            _to_markdown_table(
                rounded_candidates,
                [
                    "universe_name",
                    "continuous_return_pct",
                    "vs_prod_continuous_return_pct_delta",
                    "vs_1321_continuous_return_pct_delta",
                    "continuous_alpha_pct",
                    "avg_yearly_return_pct",
                    "avg_yearly_alpha_pct",
                    "avg_yearly_mdd_pct",
                    "continuous_mdd_pct",
                    "positive_years",
                    "continuous_stability_rank",
                ],
            )
        )
        handle.write("\n\n")

        handle.write("## Observations\n\n")
        for observation in observations:
            handle.write(f"- {observation}\n")
        handle.write("\n")

        handle.write("## Full Summary\n\n")
        handle.write(
            _to_markdown_table(
                _round_frame(combined),
                [
                    "universe_name",
                    "continuous_return_pct",
                    "continuous_alpha_pct",
                    "avg_yearly_return_pct",
                    "avg_yearly_alpha_pct",
                    "avg_yearly_mdd_pct",
                    "continuous_mdd_pct",
                    "positive_years",
                    "continuous_stability_rank",
                    "score_model",
                    "overlap_with_production",
                ],
            )
        )
        handle.write("\n")


if __name__ == "__main__":
    main()